### ISSUE TITLE
Push podspec to trunk repository

### ISSUE THREAD

**Issue by gsampaio** [edwardaux/Ogra#14]
Hey, 

I am currently creating a library that depends on Ogra and to be able to valid my `podspec` cocoapods tries to fetch Ogra on the main trunk repository. Since its not currently available whenever I try to run `pod spec lint` over my podspec it fails. 

Right now I am pointing Ogra to my company private podspec repository, but it would be really nice to be available on the main trunk repository so everyone could use it without adding the git repository reference on the Podifle. 

If you need some help doing that please let me know!

**Comment by edwardaux** [comment]
Created and merged https://github.com/edwardaux/Ogra/pull/15 and have pushed to the trunk. Give it a crack when you're ready.

**Comment by gsampaio** [comment]
Worked just fine. Thanks you very much 👍
