### ISSUE TITLE
Accessing [String: JSON]

### ISSUE THREAD

**Issue by clayellis** [edwardaux/Ogra#22]
How do you access the [String: JSON] dictionary from an object after calling `encode()` on it?

**Comment by edwardaux** [comment]
Do you mean to write it out to a file or something? There is a function on `JSON` called `JSONObject()` that returns an array of `AnyObject` that you can pass to `NSJSONSerialization.dataWithJSONObject()`. The readme has an example. 

Is that what you meant?

**Comment by edwardaux** [comment]
I assume this is not still occurring, so am closing. Feel free to re-open if you are still having problems.
