### ISSUE TITLE
Missing Podspec for 3.0.0

### ISSUE THREAD

**Issue by gsampaio** [edwardaux/Ogra#23]
Right now after search for Ogra 3.0.0 on the `master` podspec, the current version is the 2.2.0. It would be great to have the latest version available there also. 

```
-> Ogra (2.2.0)
   Provides the ability to convert from a model object into an Argo JSON representation.
   pod 'Ogra', '~> 2.2.0'
   - Homepage: https://github.com/edwardaux/Ogra
   - Source:   https://github.com/edwardaux/Ogra.git
   - Versions: 2.2.0, 2.1.0 [master repo]
```

**Comment by nickvelloff** [comment]
Yes please, having the same issue. 👍

**Comment by edwardaux** [comment]
Apologies. I thought I'd already done that. I just pushed now.
