### ISSUE TITLE
Encode two dimensional Array

### ISSUE THREAD

**Issue by gruenekampfente** [edwardaux/Ogra#26]
Hello everybody,

I wonder myself if there is a way to encode a two dimensional Array like this `[[String]]` with Ogra?

**Comment by edwardaux** [comment]
Hmmm... apologies for the delay. To be honest, I originally thought that Ogra would support this out of the box. For example, consider the following:

```
struct TestObject {
    let field1: [String]
    let field2: [[String]]
}

extension TestObject: Encodable {
    func encode() -> JSON {
        return JSON.Object([
            "field1" : self.field1.encode(),    // this compiles
            "field2" : self.field2.encode()     // this doesn't
        ])
    }
}
```

Given that `[String]` is encodable, and I have an extension defined as `extension CollectionType where Generator.Element: Encodable`, I am not sure why the 2nd line doesn't compile (it complains about an ambiguous reference).

However, you can fairly easily workaround this by manually building the array of arrays yourself:

```
extension TestObject: Encodable {
    func encode() -> JSON {
        return JSON.Object([
            "field1" : self.field1.encode(),
            "field2" : JSON.Array(self.field2.map { $0.encode() })
        ])
    }
}
```

Let me know if that doesn't work. Hope that helps (again, sorry for the delay)

**Comment by gruenekampfente** [comment]
It worked, thank you !
