### ISSUE TITLE
Any way to make Optional.None not appear in output JSON?

### ISSUE THREAD

**Issue by andrewjackman** [edwardaux/Ogra#9]
I've started coding in Swift after years of Scala, and one thing I like about Scala JSON frameworks is that they are able to map case classes directly to/from JSON, treating Options as optional in the JSON. So for example encoding to JSON:

``` scala
case class Pilot(name: String, callSign: Option[String])

val  iceMan = Pilot(name = "Val Kilmer", callSign = None)
```

would render as

``` javascript
{
    "name": "Val Kilmer"
}
```

and 

``` scala
val  iceMan = Pilot(name = "Val Kilmer", callSign = Some("Ice Man"))
```

would render as

``` javascript
{
    "name": "Val Kilmer",
    "callSign": "Ice Man"
}
```

And when parsing JSON, if a field is absent in the JSON the Optional field is set to None.

Can you recommend a way of achieving this in Swift using Argo and Ogra? I'm happy to fork your repo and contribute it back, however I'm a Swift noob, so I may need some assistance.

**Comment by edwardaux** [comment]
Bearing in mind that there is a semantic difference between a "field that doesn't exist" and a "field that does exist but happens to have a null value", you can easily achieve what you're looking for by just excluding the fields from the value returned from `encode()`. Untested code below:

```
extension Pilot: Encodable {
    func encode() -> JSON {
        var fields = [String : JSON]()
        fields["name"] = self.name.encode()
        if let callSign = self.callSign {
            fields["callSign"] = callSign.encode()
        }
        return JSON.Object(fields)
    }
}
```
